spring:
  kafka:
    bootstrap-servers: "bitstamp-consumer-1.int.herron.se:9092"
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "com.herron.bitstamp.consumer.server.model.BitstampStockInstrument"