server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      properties:
        max-request-size: 20000000

kafka:
  topic:
    audit-trail:
      nr-of-partitions: 1
      max-message-bytes: 20000000
    trade-data:
      nr-of-partitions: 1
      max-message-bytes: 20000000
    top-of-book:
      nr-of-partitions: 1
      max-message-bytes: 20000000